#!/usr/bin/python3

import sys

print(sys.argv)

print(sys.argv[0])

print(len(sys.argv))

cOption = True
wOption = True
lOption = True
mOption = False

optionsFound = False

files == []
if len(sys.argv) > 1 and sys.argv[1][0] == "-":
	cOption = False
	wOption = False
	lOption = False

lines = 0

for lines in files:
	lines = lines + 1

characters = 0

for characters in files:
	characters = len(lines)

words = 0

for words in files:
	words = len(split(lines))	
	
for arg in sys.argv:
	if arg[0] == "-":
		print(arg[0])
		if "l" in arg:
			lOption = True
for arg in sys.argv:
	if arg[0] == "-":
		print(arg[0])
		if "c" in arg:
			cOption = True
for arg in sys.argv:
	if arg[0] == "-":
		print(arg[0])
		if "w" in arg:
			wOption = True

for i in range(1, len(sys.argv)):
	if sys.argv[i][0] != "-":
		files.append(sys.argv[i])
	else:
		if not optionsFound:
			cOption = False
			wOption = False
			lOption = False
			optionsFound = True


if lOption:
	print("%3d"%lines,end="")
if cOption:
	print(" %4d"%characters,end="")
if wOption:
	print(" %3d"%words,end="")

for filename in files:
	myfile = open(filename)

if len(files == 0):
	for line in sys.stdin:

